{% set name = "greenletio" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5751773f859ee7c5a8745569af04b27532e2b8bdb170eb224193bebc32f38136

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - greenlet

test:
  imports:
    - greenletio

about:
  home: https://greenletio.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Asyncio integration with sync code using greenlets
  dev_url: https://github.com/miguelgrinberg/greenletio

extra:
  recipe-maintainers:
    - davidbrochart
